sonar.projectKey=devflow
sonar.projectName=devflow
sonar.projectVersion=1.0
sonar.host.url=http://192.168.1.208:9000
sonar.token=sqa_2e3c71c2c3155d5e8da8479f4419220ad0537c79


# Go 源码目录
sonar.sources=.

