[application]
name = devflow
port = 8080

[OpenLdap]
host = 192.168.1.71
port = 389
ou = technology
dc1 = chengdd
dc2 = com

[jwt]
; 过期时间，单位小时
expire = 12
secret = 2dd6917f09814627ab7d94c4e3532934

[aes]
secret = D0D1702422614BFAA0BD016FF5DF04AE

[mysql]
username = root
password = 1qaz@WSX
addr = 192.168.1.87
port = 3307
databases = devflow
charset = utf8

[redis]
addr = 192.168.1.102
port = 6379
db = 2

[gitlab]
username = root
password = mojory@1q2w3e4r
addr = http://gitlab.chengdd.com/api/v4/

[jenkins]
username = yen
password = 1qaz@WSX
addr = http://jenkins.chengdd.cn/

[harbor]
url = "https://harbor.chengduoduo.com"
username = "admin"
password = "Mzl123456"

[docker]
remote_port = "2375"